# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway_atuadores.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'gateway_atuadores.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17gateway_atuadores.proto\x12\nsmart_city\"\\\n\x15InformacaoDispositivo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04tipo\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\r\n\x05porta\x18\x04 \x01(\x05\x12\x0e\n\x06\x65stado\x18\x05 \x01(\t\"\xb1\x02\n\x13\x44\x65scobertaMulticast\x12\x43\n\rtipo_mensagem\x18\x01 \x01(\x0e\x32,.smart_city.DescobertaMulticast.TipoMensagem\x12\x12\n\nip_gateway\x18\x02 \x01(\t\x12\x19\n\x11porta_gateway_tcp\x18\x03 \x01(\x05\x12\x41\n\x16informacao_dispositivo\x18\x04 \x01(\x0b\x32!.smart_city.InformacaoDispositivo\"c\n\x0cTipoMensagem\x12\x1f\n\x1bTIPO_MULTICAST_DESCONHECIDO\x10\x00\x12\x19\n\x15REQUISICAO_DESCOBERTA\x10\x01\x12\x17\n\x13RESPOSTA_DESCOBERTA\x10\x02\"\xe1\x01\n\x0e\x43omandoAtuador\x12\x16\n\x0eid_dispositivo\x18\x01 \x01(\t\x12\x43\n\x0ctipo_comando\x18\x02 \x01(\x0e\x32-.smart_city.ComandoAtuador.TipoComandoAtuador\x12\r\n\x05valor\x18\x03 \x01(\t\"c\n\x12TipoComandoAtuador\x12 \n\x1c\x43OMANDO_ATUADOR_DESCONHECIDO\x10\x00\x12\x12\n\x0eLIGAR_DESLIGAR\x10\x01\x12\x17\n\x13\x44\x45\x46INIR_TEMPERATURA\x10\x02\"t\n\x1c\x41tualizacaoEstadoDispositivo\x12\x16\n\x0eid_dispositivo\x18\x01 \x01(\t\x12\x14\n\x0c\x65stado_atual\x18\x02 \x01(\t\x12\x15\n\rvalor_leitura\x18\x03 \x01(\x02\x12\x0f\n\x07unidade\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_atuadores_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFORMACAODISPOSITIVO']._serialized_start=39
  _globals['_INFORMACAODISPOSITIVO']._serialized_end=131
  _globals['_DESCOBERTAMULTICAST']._serialized_start=134
  _globals['_DESCOBERTAMULTICAST']._serialized_end=439
  _globals['_DESCOBERTAMULTICAST_TIPOMENSAGEM']._serialized_start=340
  _globals['_DESCOBERTAMULTICAST_TIPOMENSAGEM']._serialized_end=439
  _globals['_COMANDOATUADOR']._serialized_start=442
  _globals['_COMANDOATUADOR']._serialized_end=667
  _globals['_COMANDOATUADOR_TIPOCOMANDOATUADOR']._serialized_start=568
  _globals['_COMANDOATUADOR_TIPOCOMANDOATUADOR']._serialized_end=667
  _globals['_ATUALIZACAOESTADODISPOSITIVO']._serialized_start=669
  _globals['_ATUALIZACAOESTADODISPOSITIVO']._serialized_end=785
# @@protoc_insertion_point(module_scope)
