# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gateway_atuadores_pb2 as gateway__atuadores__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in gateway_atuadores_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AtuadorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ligar = channel.unary_unary(
                '/atuador.AtuadorService/Ligar',
                request_serializer=gateway__atuadores__pb2.Empty.SerializeToString,
                response_deserializer=gateway__atuadores__pb2.Resposta.FromString,
                _registered_method=True)
        self.Desligar = channel.unary_unary(
                '/atuador.AtuadorService/Desligar',
                request_serializer=gateway__atuadores__pb2.Empty.SerializeToString,
                response_deserializer=gateway__atuadores__pb2.Resposta.FromString,
                _registered_method=True)
        self.AlterarConfiguracao = channel.unary_unary(
                '/atuador.AtuadorService/AlterarConfiguracao',
                request_serializer=gateway__atuadores__pb2.ConfiguracaoRequest.SerializeToString,
                response_deserializer=gateway__atuadores__pb2.Resposta.FromString,
                _registered_method=True)
        self.ConsultarEstado = channel.unary_unary(
                '/atuador.AtuadorService/ConsultarEstado',
                request_serializer=gateway__atuadores__pb2.Empty.SerializeToString,
                response_deserializer=gateway__atuadores__pb2.EstadoResponse.FromString,
                _registered_method=True)


class AtuadorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ligar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Desligar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AlterarConfiguracao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarEstado(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AtuadorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ligar': grpc.unary_unary_rpc_method_handler(
                    servicer.Ligar,
                    request_deserializer=gateway__atuadores__pb2.Empty.FromString,
                    response_serializer=gateway__atuadores__pb2.Resposta.SerializeToString,
            ),
            'Desligar': grpc.unary_unary_rpc_method_handler(
                    servicer.Desligar,
                    request_deserializer=gateway__atuadores__pb2.Empty.FromString,
                    response_serializer=gateway__atuadores__pb2.Resposta.SerializeToString,
            ),
            'AlterarConfiguracao': grpc.unary_unary_rpc_method_handler(
                    servicer.AlterarConfiguracao,
                    request_deserializer=gateway__atuadores__pb2.ConfiguracaoRequest.FromString,
                    response_serializer=gateway__atuadores__pb2.Resposta.SerializeToString,
            ),
            'ConsultarEstado': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarEstado,
                    request_deserializer=gateway__atuadores__pb2.Empty.FromString,
                    response_serializer=gateway__atuadores__pb2.EstadoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'atuador.AtuadorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('atuador.AtuadorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AtuadorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ligar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atuador.AtuadorService/Ligar',
            gateway__atuadores__pb2.Empty.SerializeToString,
            gateway__atuadores__pb2.Resposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Desligar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atuador.AtuadorService/Desligar',
            gateway__atuadores__pb2.Empty.SerializeToString,
            gateway__atuadores__pb2.Resposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AlterarConfiguracao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atuador.AtuadorService/AlterarConfiguracao',
            gateway__atuadores__pb2.ConfiguracaoRequest.SerializeToString,
            gateway__atuadores__pb2.Resposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarEstado(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atuador.AtuadorService/ConsultarEstado',
            gateway__atuadores__pb2.Empty.SerializeToString,
            gateway__atuadores__pb2.EstadoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
