# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway_atuadores.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'gateway_atuadores.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17gateway_atuadores.proto\x12\x07\x61tuador\"\x07\n\x05\x45mpty\"7\n\x13\x43onfiguracaoRequest\x12\x11\n\tparametro\x18\x01 \x01(\t\x12\r\n\x05valor\x18\x02 \x01(\t\"-\n\x08Resposta\x12\x10\n\x08mensagem\x18\x01 \x01(\t\x12\x0f\n\x07sucesso\x18\x02 \x01(\x08\"\x99\x01\n\x0e\x45stadoResponse\x12\x0e\n\x06\x65stado\x18\x01 \x01(\t\x12\x41\n\rconfiguracoes\x18\x02 \x03(\x0b\x32*.atuador.EstadoResponse.ConfiguracoesEntry\x1a\x34\n\x12\x43onfiguracoesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xef\x01\n\x0e\x41tuadorService\x12*\n\x05Ligar\x12\x0e.atuador.Empty\x1a\x11.atuador.Resposta\x12-\n\x08\x44\x65sligar\x12\x0e.atuador.Empty\x1a\x11.atuador.Resposta\x12\x46\n\x13\x41lterarConfiguracao\x12\x1c.atuador.ConfiguracaoRequest\x1a\x11.atuador.Resposta\x12:\n\x0f\x43onsultarEstado\x12\x0e.atuador.Empty\x1a\x17.atuador.EstadoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_atuadores_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ESTADORESPONSE_CONFIGURACOESENTRY']._loaded_options = None
  _globals['_ESTADORESPONSE_CONFIGURACOESENTRY']._serialized_options = b'8\001'
  _globals['_EMPTY']._serialized_start=36
  _globals['_EMPTY']._serialized_end=43
  _globals['_CONFIGURACAOREQUEST']._serialized_start=45
  _globals['_CONFIGURACAOREQUEST']._serialized_end=100
  _globals['_RESPOSTA']._serialized_start=102
  _globals['_RESPOSTA']._serialized_end=147
  _globals['_ESTADORESPONSE']._serialized_start=150
  _globals['_ESTADORESPONSE']._serialized_end=303
  _globals['_ESTADORESPONSE_CONFIGURACOESENTRY']._serialized_start=251
  _globals['_ESTADORESPONSE_CONFIGURACOESENTRY']._serialized_end=303
  _globals['_ATUADORSERVICE']._serialized_start=306
  _globals['_ATUADORSERVICE']._serialized_end=545
# @@protoc_insertion_point(module_scope)
