# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cliente_gateway.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'cliente_gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63liente_gateway.proto\x12\x0f\x63liente_gateway\"\xe3\x01\n\x11\x43lienteRequisicao\x12G\n\x0crequest_type\x18\x01 \x01(\x0e\x32\x31.cliente_gateway.ClienteRequisicao.TipoRequisicao\x12)\n\x07\x63omando\x18\x02 \x01(\x0b\x32\x18.cliente_gateway.Comando\"Z\n\x0eTipoRequisicao\x12\x1b\n\x17REQUISICAO_DESCONHECIDA\x10\x00\x12\x17\n\x13LISTAR_DISPOSITIVOS\x10\x01\x12\x12\n\x0e\x45NVIAR_COMANDO\x10\x02\"\x96\x02\n\x0fRespostaGateway\x12\x46\n\rresponse_type\x18\x01 \x01(\x0e\x32/.cliente_gateway.RespostaGateway.TipoRequisicao\x12\x10\n\x08successo\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x31\n\x07\x64\x65vices\x18\x04 \x03(\x0b\x32 .cliente_gateway.DispositivoInfo\"e\n\x0eTipoRequisicao\x12\x1b\n\x17REQUISICAO_DESCONHECIDA\x10\x00\x12\x17\n\x13LISTAR_DISPOSITIVOS\x10\x01\x12\x12\n\x0e\x45NVIAR_COMANDO\x10\x02\x12\t\n\x05\x45RROR\x10\x03\"\xc1\x01\n\x07\x43omando\x12\x16\n\x0eid_despositivo\x18\x01 \x01(\t\x12:\n\x0c\x43omando_type\x18\x02 \x01(\x0e\x32$.cliente_gateway.Comando.TipoComando\x12\r\n\x05value\x18\x03 \x01(\t\"S\n\x0bTipoComando\x12\x18\n\x14\x43OMANDO_DESCONHECIDO\x10\x00\x12\x13\n\x0f\x41LTERNA_ENERGIA\x10\x01\x12\x15\n\x11SETAR_TEMPERATURA\x10\x02\"V\n\x0f\x44ispositivoInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04tipo\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\r\n\x05porta\x18\x04 \x01(\x05\x12\x0e\n\x06\x65stado\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cliente_gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTEREQUISICAO']._serialized_start=43
  _globals['_CLIENTEREQUISICAO']._serialized_end=270
  _globals['_CLIENTEREQUISICAO_TIPOREQUISICAO']._serialized_start=180
  _globals['_CLIENTEREQUISICAO_TIPOREQUISICAO']._serialized_end=270
  _globals['_RESPOSTAGATEWAY']._serialized_start=273
  _globals['_RESPOSTAGATEWAY']._serialized_end=551
  _globals['_RESPOSTAGATEWAY_TIPOREQUISICAO']._serialized_start=450
  _globals['_RESPOSTAGATEWAY_TIPOREQUISICAO']._serialized_end=551
  _globals['_COMANDO']._serialized_start=554
  _globals['_COMANDO']._serialized_end=747
  _globals['_COMANDO_TIPOCOMANDO']._serialized_start=664
  _globals['_COMANDO_TIPOCOMANDO']._serialized_end=747
  _globals['_DISPOSITIVOINFO']._serialized_start=749
  _globals['_DISPOSITIVOINFO']._serialized_end=835
# @@protoc_insertion_point(module_scope)
