# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Protos/cliente_gateway.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'Protos/cliente_gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cProtos/cliente_gateway.proto\x12\x0f\x63liente_gateway\"\xf2\x01\n\x11\x43lienteRequisicao\x12G\n\x0crequest_type\x18\x01 \x01(\x0e\x32\x31.cliente_gateway.ClienteRequisicao.TipoRequisicao\x12\x38\n\x0f\x63omando_cliente\x18\x02 \x01(\x0b\x32\x1f.cliente_gateway.ComandoCliente\"Z\n\x0eTipoRequisicao\x12\x1b\n\x17REQUISICAO_DESCONHECIDA\x10\x00\x12\x17\n\x13LISTAR_DISPOSITIVOS\x10\x01\x12\x12\n\x0e\x45NVIAR_COMANDO\x10\x02\"\xd0\x01\n\x0e\x43omandoCliente\x12\x16\n\x0eid_dispositivo\x18\x01 \x01(\t\x12\x41\n\x0ctipo_comando\x18\x02 \x01(\x0e\x32+.cliente_gateway.ComandoCliente.TipoComando\x12\r\n\x05valor\x18\x03 \x01(\t\"T\n\x0bTipoComando\x12\x18\n\x14\x43OMANDO_DESCONHECIDO\x10\x00\x12\x12\n\x0eLIGAR_DESLIGAR\x10\x01\x12\x17\n\x13\x44\x45\x46INIR_TEMPERATURA\x10\x02\"\x94\x02\n\x0fRespostaGateway\x12\x46\n\rresponse_type\x18\x01 \x01(\x0e\x32/.cliente_gateway.RespostaGateway.TipoRequisicao\x12\x0f\n\x07sucesso\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x31\n\x07\x64\x65vices\x18\x04 \x03(\x0b\x32 .cliente_gateway.DispositivoInfo\"d\n\x0eTipoRequisicao\x12\x1b\n\x17REQUISICAO_DESCONHECIDA\x10\x00\x12\x17\n\x13LISTAR_DISPOSITIVOS\x10\x01\x12\x12\n\x0e\x45NVIAR_COMANDO\x10\x02\x12\x08\n\x04\x45RRO\x10\x03\"V\n\x0f\x44ispositivoInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04tipo\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\r\n\x05porta\x18\x04 \x01(\x05\x12\x0e\n\x06\x65stado\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protos.cliente_gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTEREQUISICAO']._serialized_start=50
  _globals['_CLIENTEREQUISICAO']._serialized_end=292
  _globals['_CLIENTEREQUISICAO_TIPOREQUISICAO']._serialized_start=202
  _globals['_CLIENTEREQUISICAO_TIPOREQUISICAO']._serialized_end=292
  _globals['_COMANDOCLIENTE']._serialized_start=295
  _globals['_COMANDOCLIENTE']._serialized_end=503
  _globals['_COMANDOCLIENTE_TIPOCOMANDO']._serialized_start=419
  _globals['_COMANDOCLIENTE_TIPOCOMANDO']._serialized_end=503
  _globals['_RESPOSTAGATEWAY']._serialized_start=506
  _globals['_RESPOSTAGATEWAY']._serialized_end=782
  _globals['_RESPOSTAGATEWAY_TIPOREQUISICAO']._serialized_start=682
  _globals['_RESPOSTAGATEWAY_TIPOREQUISICAO']._serialized_end=782
  _globals['_DISPOSITIVOINFO']._serialized_start=784
  _globals['_DISPOSITIVOINFO']._serialized_end=870
# @@protoc_insertion_point(module_scope)
